### ISSUE TITLE
how to use python codes to interface with arduino uno

### ISSUE THREAD

**Issue by SunilKumarAmpolu** [ramonidea/LI-FI-Arduino#1]
I'm trying to run the transmitter and receiver python programmes in python..

while running transmitter.py code given in code section, i'm getting error like

****Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\Transmitter.py", line 36, in <module>
    ser = serial.Serial('COM4',115200,timeout=.1) #Begin the Serial connection
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM4': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)****

while running pypic.py code,it is showing error

**Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\Pypic.py", line 15, in <module>
    ser = serial.Serial('COM3', 115200, timeout=.1) # Start the serial connectiion
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\serial\serialwin32.py", line 31, in __init__
    super(Serial, self).__init__(*args, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\serial\serialutil.py", line 240, in __init__
    self.open()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM3': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)**

please help me what to do

**Comment by ramonqu7** [comment]
You need to find the COM number from your computer first and then use it. 

And also in this project, I only used one laptop to control both transmitter and receiver.
